services:
  habitus:
    git_repo: https://github.com/kamerblauwlicht/habitus-test.git
    git_branch: master
    env_vars:
      HABITUS_VERY_SECRET_STUFF: launch_codes
    use_habitus: true
    use_habitus_step: builder